language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
script: bundle exec rspec
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-18mode
    - rvm: 2.1.0-preview2
